baseURL = 'https://victorponz.github.io/symfony-teoria/'
languageCode = 'en-us'
title = 'Programación en JAVA'
theme = 'victor'
enableGitInfo = true
[params]
  GitHubURL = 'https://github.com/victorponz/symfony-teoria'
  baseDir = 'symfony-teoria'
